s is a YAML file. It has two annoying rules:
#  - It must have a line of three hyphens at the beginning
#  - Line indentation _must_ be spaces and not tabs.
---
# Where to look for scripts and templates:
scripts_dir: /home/avi/bin/sitecreator/etc/scripts/
templates_dir: /home/avi/bin/sitecreator/etc/scripts/templates

# Passwords that will need to be generated. These are created 
# according to options here, but 
passwords:
 mysql:
  length: 12
 mysqldev:
  length: 12
 unix:
  length: 9


# Scripts to run, in the order in which they should be run. There
# are some placeholders to use to have arguments sent to the scripts:
#	%DOMAINS        a space-separated list of domains, including aliases
#                       the first member of the list is the domain passed as
#                       the argument, followed by those specified by -a
#	%USERNAME       username
#	%TEMPLATES_DIR  templates directory
#	%PASSWORD_xxx   generate a password. The 'xxx' must be listed in the 'passwords'
#		        section
scripts:
 - create_unix_user.sh %USERNAME%
 - create_mysql.sh %USERNAME% %PASSWORD_mysql%
 - create_mysql.sh %USERNAME_dev %PASSWORD_mysqldev
 - create_apache_vhost.pl %USERNAME% %TEMPLATES_DIR% %DOMAINS%
 - restart_apache.sh
 - add_ssh_keys.sh %USERNAME% %TEMPLATES_DIR%


apache:
  testurldomain: /bin/hostname 
